apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: temporary-iguana-dotnet-basic
  janus-idp.io/tekton: temporary-iguana-dotnet-basic
  backstage.io/kubernetes-id: temporary-iguana-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-demo 
  app.kubernetes.io/part-of: temporary-iguana-dotnet-basic
resources: 
- deployment.yaml
- route.yaml
- service.yaml
